### ISSUE TITLE
 When Engine starts, a Plugin configured as `Running` does not have access to its `RunningStatus`/`LivePluginInfo` (Has workaround)

### ISSUE THREAD

**Issue by bcrosnier** [Invenietis/yodii#5]
# Description

A`IYodiiPlugin` that wants access to its `RunningStatus` (eg. to know whether it is `Running` or `RunningLocked`), which is on its own `LivePluginInfo`, cannot access it through injected `IYodiiEngine` when the engine configuration requires the plugin to be running.

The `ILiveInfo.Plugins` and `ILiveInfo.Services` collections are not populated during startup, so `ILiveInfo.FindPlugin()` predictably returns `null`.

The issue does not appear when starting the `IYodiiPlugin` _after_ starting the `IYodiiEngine`.
# Procedure

With a manual plugin start:
1. Create `IYodiiPlugin`
2. Create `YodiiEngine`, `YodiiHost`, set up `Discoverer` with plugin assembly
3. Start `YodiiEngine`
4. Start `IYodiiPlugin` using `YodiiEngine.Start()` and wait for success
5. When `IYodiiPlugin.Start()` is called, the plugin has access to its own `LivePluginInfo`

With an automatic plugin start:
1. Create `IYodiiPlugin`
2. Create `YodiiEngine`, `YodiiHost`, set up `Discoverer` with plugin assembly
3. Set `YodiiConfiguration` to take the plugin as `Running`
4. Start `YodiiEngine`
5. When `IYodiiPlugin.Start()` is called, the plugin cannot acces its own `LivePluginInfo`
# Workaround

A workaround is possible: bind on injected `IYodiiEngine` and its `IYodiiEngine.PropertyChanged` event, and wait for the `IsRunning` property to become `true`.

See https://github.com/Invenietis/yodii/commit/bbdaa18b9e9e0498a09ae32144328efca8e34e71#diff-3cc0de3900676ee87deb6f9a7c553283R143

With this workaround, however, you cannot reliably determine if the `IYodiiPlugin` that implements it is `Running` or `RunningLocked` during startup.
## Workaround application

For a `IYodiiPlugin` that spawns a window when it starts, I wanted to disable the Close button of the new Window depending on whether the plugin can stop or not. In the current implementation, the Window is created when the plugin starts, even if the engine is not finished starting.

**Comment by olivier-spinelli** [comment]
To solve this, we'll have to change the engine/host interactions.
Engine's internal DynamicSolverResult will expose a simple list of <IPluginInfo,RunningStatus> instead of the 3 lists (Disabled/Running/Stopped).
The host.Apply will work on this list: it will then be able to expose the RunningStatus on the PluginProxy object (that is the IYodiiEngine per plugin interface) AND on the (Pre)Start/StopContext arguments.

On the IYodiiEngine(Proxy?), exposing the RunningStatus seems a little bit overkill: only Running/RunningLoked can actually be accessible to a plugin... 
So we'll expose only a CanStop property (and its CanStopChanged event).

**Comment by bcrosnier** [comment]
Fixed in https://github.com/Invenietis/yodii/commit/9740feb2f155f271bbfef2c7f993d541f0239062 and https://github.com/Invenietis/yodii/commit/d77d481359c9c47bf5674186b6b477ba115df697.
